module.exports = {
    addScannerListener: 'add-scanner-listener',
    removeScannerListener: 'remove-scanner-listener',
    getDbStatus: 'get-db-status',
    getDbStatusDone: 'get-db-status-done',
    getConfiguration: 'get-configuration',
    getConfigurationDone: 'get-configuration-done',
    updateConfiguration: 'update-configuration',
    updateConfigurationDone: 'update-configuration-done',
    scan: 'scan',
    addCustomer: 'add-customer',
    addCustomerDone: 'add-customer-done',
    exportDatabase: 'export-database',
    exportDatabaseDone: 'export-database-done',
    getDeviceStatus: 'device-status',
    getDeviceStatusDone: 'device-status-done',
    reloadDevice: 'reload-device',
    reloadDeviceDone: 'reload-device-done',
    simulateScan: 'simulate-scan',
};
